### PR TITLE
fix: Tag fetching

### LINKED ISSUE #17: Tag fetching
When the `verify_versions.py` script fetches tags of a mod repository, it only accesses the first tag page (*e.g.* https://api.github.com/repos/{}/{}/tags), while tags resource is paginated (*i.e.* searched tag might not be on the first results page).

See https://github.com/R2Northstar/VerifiedMods/pull/16#issuecomment-1884912482 for pages example.

### PR DESCRIPTION
**Pull request by Alystrasz**
**META PR, NO MOD VERIFICATION NEEDED**

While checking tags, if current tag isn't found in first page, script will now browse all API pages until either tag is found or there are no more pages.

I also added a few tests to ensure correct method behaviour.

Closes #17.

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
I'm maybe gonna split this PR up a bit before merging ^^

Also, I think for unit testing there's some frameworks like `pytest` that make it a bit nicer so that we don't have to pass a CLI arg to run unittest. Then we can also combine it with our current CI to always run meta tests for verification scripts ^^

**Comment by Alystrasz** [comment]
> Then we can also combine it with our current CI to always run meta tests for verification scripts

I feel like this is overkill tbh, the idea was to ensure new function behaves properly during development.

**Comment by GeckoEidechse** [comment]
I'm gonna remove the testing into separate PR and then merge this one ^^

**Review by GeckoEidechse — APPROVED** [review]
Aight, I think I have massacred this PR enough now xD

Anyway, code works and as far as I can tell the logic is correct ^^

The unit testing code for this will be added in a separate PR.

**Comment by GeckoEidechse** [comment]
Also I'll change the `.format()` parts to f-strings as well in a separate PR ^^

**Pull request merged**
