### PR TITLE
LTS Rebalance v1.0.9 (New Verification)

### PR DESCRIPTION
**Pull request by Dinorush**
# LTS Rebalance v1.0.9

## Did I read the whole README file and understood all of its content?
YES

## Did I update verified-mods.json with my new mod's information?
YES

## Has a previous version of my mod been previously verified?
NO

## Mod description
"Rebalances titans for better meta diversity, especially in LTS." Also of note is that it currently has a small client-side mod packaged alongside Rebalance that reparses weapon KeyValues when Rebalance is enabled/disabled at the main menu (since Northstar does not do this currently). I don't imagine it is an issue, but I figured I should mention it just in case someone is wondering what KVFix does.

## Thunderstore link
https://northstar.thunderstore.io/package/Dinorush/LTS_Rebalance/

### CODE REVIEW

**Comment by Alystrasz** [comment]
@Dinorush automatic verification failed because your `v1.0.7` release is tagged as `v1.0.7`, while it should be tagged as `1.0.7` (with no leading `v`).
Fixing this should solve the issue :)

**Comment by ASpoonPlaysGames** [comment]
Does LTS rebalance still have the issue of needing a full game restart to work properly?

**Comment by Dinorush** [comment]
To your point Spoon, that is technically not the case. It requires `weapon_reparse` to run before connecting to a server with different weapon key values. KVFix ensures everything is OK if you enable/disable it on the main menu. Connecting to a server that turns off or on a client required mod which changes weapon key values has not worked for a long time, as the reparse that gets called never goes through. I don't know if that issue ever got fixed. Both issues, actually, are present in base Northstar. The difference is that I've fixed the one I can with KVFix, the other requires a PR to Northstar. I believe Bob found the same bandaid fix I use in KVFix to get reload mods to reparse the weapons, but iirc he wanted to remake the command entirely (and never finished it). May be worth investigating any fix we can get, as key value desyncs will affect any mod adds weapon attachments or modifies values which sync with the server.

**Comment by Dinorush** [comment]
From the looks of it, the python script failed because the "v" tags are prioritized so the new tag got pushed out of the initial fetched batch.

Schema failed cuz capital letters, that one's an easy fix, the other I'll look into

**Comment by Alystrasz** [comment]
Script could not find the `1.0.8` tag in the tags list (https://api.github.com/repos/Dinorush/LTSRebalance/tags).
I feel like I have a paging issue here...

**Comment by Dinorush** [comment]
Well I renamed all my tags to remove the leading `v`, and consequently nuked the relationship between my releases and their tags, so rip public git release history. At least I can still scroll through the release drafts myself lol

**Comment by Alystrasz** [comment]
I'm sorry you nuked your release history :smile:
At least all lights are green for your PR to be reviewed now.

About that tags pagination, I would like to avoid fetching pages one by one, but I can't find a "sort by newest" option, so I'll probably have to do that in the end

**Comment by L1ghtman2k** [comment]
A game restart might be temporarily needed here until kv issue is addressed?

**Comment by Dinorush** [comment]
KVFix will at least fix it for Rebal if you reload the multiplayer lobby, so it doesn't quite need a full restart, but any normal mod that requires reparsing to prevent desync will.

**Comment by Alystrasz** [comment]
A simple way to check if it's working is by trying:
```text
.\NorthstarLauncher.exe -customverifiedurl=https://raw.githubusercontent.com/Dinorush/VerifiedMods/LTSRebalance/verified-mods.json
```
I could check that mod was correctly downloaded, but not if a game restart was needed, since I couldn't find a public server.

**Comment by Alystrasz** [comment]
> A simple way to check if it's working is by trying:
> 
> ```
> .\NorthstarLauncher.exe -customverifiedurl=https://raw.githubusercontent.com/Dinorush/VerifiedMods/LTSRebalance/verified-mods.json
> ```
> 
> I could check that mod was correctly downloaded, but not if a game restart was needed, since I couldn't find a public server.

@Dinorush could you try the above and confirm it does work?

**Review by Alystrasz — APPROVED** [review]
Looking at the Squirrel files, I didn't spot obvious malicious behaviour. There's no use of "dangerous" [^1] functions.

As usual, _verification_ does not ensure correctness, only non-malicious behaviour. Correctness is responsibility of the mod author.

New mod entry was tested by spawning a server requiring both LTS mods, then starting northstar client with modified manifesto as argument:
```text
.\NorthstarLauncher.exe -customverifiedurl=https://raw.githubusercontent.com/Dinorush/VerifiedMods/LTSRebalance/verified-mods.json
```

Then, I could access the server through mod auto-downloading.

[^1]: e.g.: Safe I/O stuff and SquirrelHTTP. "dangerous" is a bit too much maybe. Under the assumption that the native implementations are correct and secure, there's nothing dangerous here. However it's always recommended to use more of a Swiss cheese approach and also operate a bit under the assumption that a layer can fail.

**Pull request merged**
