### PR TITLE
feat: Adjust JSON structure to allow for other mod sources

### LINKED ISSUE #22: Preparing support for alternative download sources
See https://github.com/R2Northstar/NorthstarLauncher/discussions/635

### PR DESCRIPTION
**Pull request by GeckoEidechse**
META PR, no verification needed (although it does touch `verified-mods.json`, so give it a double check nevertheless)

Will require an update to launcher as well.

Closes #22 as it adjusts the project to allow other sources in the future.
(Does not add another source in itself though)

Requires:
- Launcher PR with updated logic: https://github.com/R2Northstar/NorthstarLauncher/pull/642

**Do NOT merge until corresponding launcher PR has been merged and released and Parkour event has concluded.**

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Marking as ready for review for discussion etc but should not be merged until the conditions in PR descriptions have been met ^^

**Comment by GeckoEidechse** [comment]
cc @EM4Volts

**Comment by Alystrasz** [comment]
Instead of having a `thunderstore` member and one member per platform that will invariably lead to code duplication, shouldn't we agree on a manifest format that is platform agnostic?

**Comment by ASpoonPlaysGames** [comment]
> Instead of having a `thunderstore` member and one member per platform that will invariably lead to code duplication, shouldn't we agree on a manifest format that is platform agnostic?

That's not really up to us though, different platforms may enforce different identifiers for mods, code duplication to some degree is pretty inevitable

**Comment by Alystrasz** [comment]
> That's not really up to us though, different platforms may enforce different identifiers for mods, code duplication to some degree is pretty inevitable

Do you have any kind of identifier in mind?
Lemme try to propose some kind of format.

**Comment by Alystrasz** [comment]
Ok so the issue of the current implementation is that it only considers thunderstore (launcher too, since it builds thunderstore mod download URL using `DependencyPrefix` and `Version` members from manifest); explicitely mentioning them in the manifest would theorically allow us to support any platform:

```json5
{
    "Odd.s2space": {
        // Repository of the source code, must be public
        "Repository": "https://github.com/uniboi/s2space",
        "Versions": [
            {
                "Version": "0.0.5",

                // Ensure corresponding release exists on source repo
                "CommitHash": "f27b8f1f05d5278aa8f47ead2d9e70f39f274173",

                // Direct download URI, used by launcher to download mod
                "DownloadLink": "https://gcdn.thunderstore.io/live/repository/packages/odds-s2space-0.0.5.zip",

                // Archive checksum, used by launcher to verify mod integrity
                "Checksum": "670987e07806e8dffcb591bad8724f29abc18d9baa304d9ab4fae7804bd86bc2"
            },
            {
                "Version": "1.0.0",
                "CommitHash": "0eca593ac1666aeeaa061a5c545d917d47d6d113",
                "DownloadLink": "https://whatever.my.platform.is/packages/odds-s2space-1.0.0.zip",
                "Checksum": "eef8ae5a88df68b249529f31713d0219b18391202dfeedc2d109936c729c571c"
            },
            ...
        ]
    }
}
```

**Comment by Alystrasz** [comment]
I thought the point of the https://github.com/R2Northstar/Northstar/discussions/618 discussion was to have a unified format for all mods, no matter where they come from?

Regarding the mod format changing from platform to platform, to me, it is the responsiblity of mod managers to format said mods to match the unified, agreed-upon format.

**Comment by GeckoEidechse** [comment]
> I thought the point of the [R2Northstar/Northstar#618](https://github.com/R2Northstar/Northstar/discussions/618) discussion was to have a unified format for all mods, no matter where they come from?

We are still quite a bit away from that though. Like we haven't even started out hashing out the standard yet and I don't we want MAD[^1] to be held back by that ^^"

[^1]: mod-auto-download

&nbsp;

> Regarding the mod format changing from platform to platform, to me, it is the responsiblity of mod managers to format said mods to match the unified, agreed-upon format.

Given that we're talking about verified mods here, wouldn't the "mod manager" in this case be Northstar itself as verified mods are for MAD which is handled by Northstar itself? Or am I missing something here?

**Comment by GeckoEidechse** [comment]
Something that came to mind right now, having top level keys per platform like `thunderstore` or `github`, also means that we could always just add another key like `generic` for downloading zip from any HTTP server, exactly like proposed in your suggestion.

While I'm still strongly in favour to limiting verified mods to only certain platforms, should we ever decide to move to the generic solution, we could simply keep the existing format and just only extend the `generic` key allowing for further backwards compatibility for older verified mods ^^

**Comment by ASpoonPlaysGames** [comment]
> I thought the point of the [R2Northstar/Northstar#618](https://github.com/R2Northstar/Northstar/discussions/618) discussion was to have a unified format for all mods, no matter where they come from?

Yes but even still, platforms have their own requirements. As an example, TS requires an icon.png file in the root of the package. Even if we have a unified mod format, different platforms will package the same mod in different ways, and we therefore need different ways to handle this

**Comment by Alystrasz** [comment]
Yeah kinda agree with both of you on that, but it's the launcher who needs to handle different platform mod formats, not this repository

**Comment by GeckoEidechse** [comment]
Yeah, and so splitting the sources into different categories in the JSON allows us keep the code in launcher simple and easily extendible, as we don't need to add any logic that first tries to figure out what specific platform a download source is coming from ^^

**Comment by Alystrasz** [comment]
The launcher would still need to install mod from different format, and since figuring out the platform from download URL is straightforward, I don't get your point

**Comment by GeckoEidechse** [comment]
Idk, I find parsing strings/URLs a bit annoying...

In the end, it boils down to how we wanna structure the data.

If we don't make the platform identifier the root key, I'd still suggest having it in the object that defines the mod so that we don't have to deal with parsing the download URL but rather can just generate it ourselves.

This is especially useful when the platform URL might change like for example for us the Thunderstore URL is `https://northstar.thunderstore.io/` but for _Lethal Company_ it's `https://thunderstore.io/c/lethal-company/` [^1]. Not sure if we ever get moved over but if we would be, old links might break so keep stuff like that in mind I guess.

[^1]: https://thunderstore.io/c/northstar/ works for Northstar as well btw ^^

Also the mods on the platform might not all follow the same structure. Like with the proposed mod rewrite, old mods will have a different layout then newer ones until re-verified, meaning we either drop all old mods in the process or offer an identifier like `thunderstore-legacy` during the transition period.

With using platform identifier as root key we could also nicely match it up with how we could place mods in the remote mods dir like [mentioned above](https://github.com/R2Northstar/VerifiedMods/pull/23#issuecomment-1912215022) so we can keep them properly namespaced.


That being said, I don't have the resources atm to refactor this PR if we feel like we should have a different layout than the one proposed in this PR rn.
Feel free to give it a shot though. You might also wanna consider just asking around in `#development` channel which format would be preferred ^^"

**Comment by GeckoEidechse** [comment]
Superseded by #41

**Pull request closed without merging**
