### PR TITLE
Verify Nyami11-mp_brick-1.0.2

### PR DESCRIPTION
**Pull request by Nyami11**
# nyami.mp_brick v1.0.1

## Did I read the whole README file and understood all of its content?
YES

## Did I update verified-mods.json with my new mod's information?
YES... I think

## Has a previous version of my mod been previously verified?
NO

## Mod description
Just a simple custom map.

## Thunderstore link

https://northstar.thunderstore.io/package/Nyami11/mp_brick/

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
First custom map for verification, let's goooo :D

On that note, please forgive us if we take a bit longer on this one as we never verified custom maps before and unlock Squirrel code, maps are essentially "compiled" meaning it's a bit more difficult to check the "source" ^^"

**Comment by Nyami11** [comment]
I can send or upload the .map and texture files if you need it, I wasn't sure if I was supposed to upload that to github. It's my first time messing with VPK files, and it's the first mod I upload to thunderstore... Sorry if I do something wrong

**Comment by GeckoEidechse** [comment]
> I can send or upload the .map and texture files if you need it

Definitely feel free to ig ^^

> I wasn't sure if I was supposed to upload that to github

tbh, I don't know either xD
We're still figuring that part out, haha

**Comment by Alystrasz** [comment]
##### What I checked so far

* CI verifications are all green
* Commit hash is OK
* Checksum is OK
* Mod is correctly downloaded when joining a server requiring the mod (thanks for setting a server up btw :))
* No malicious scripts inside mod itself (there's an `example.nut` file that could be removed, but that's not a problem for verification)
* No malicious scripts found inside VMTs

##### What's left to verify

* BSP verification
* RPAK verification

**Comment by GeckoEidechse** [comment]
For the future, as far as I know, packing textures into the VPKs shouldn't be needed. I think we are still gonna finish verification but for future versions of the mods, it's probably best to just use the files directly without packing them into VPKs.

**Review by Alystrasz — APPROVED** [review]
> ##### What's left to verify
> * BSP verification
> * RPAK verification

I manually verified those yesterday night, no scripts were found.
I *hereby* declare this mod verified.

**Pull request merged**
